# 应用服务 WEB 访问端口
server:
  port: 9092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.20.192.1:8848 # Nacos 服务器地址 连接到指定 nacos 服务
        namespace: 77fa154c-5a21-4694-b2ac-db6c0e07b077 # 命名空间 隔离不同环境配置和服务注册
        # group: # 服务分组 用于逻辑分组
        # cluster-name: # 集群名称
        metadata:
          my-meta-key: my-data-value # 自定义元数据,用于实现动态路由等功能
        service: student # 服务名称 用于在注册中心注册和发现服务
        username: nacos # nacos 配置中心的用户名
        password: nacos # nacos 配置中心的密码
        port: 9092 # 本服务端口号
        weight: 1 # 权重,用于负载均衡,可以配置不同实例的权重,影响调用的分发比例
        ephemeral: true # 是否为临时实例,即是否自动摘除不健康实例


