# 应用服务 WEB 访问端口
server:
  port: 9093

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080   # 控制台地址
      web-context-unify: false  # 使用链路控制流量时 关闭context上下文语境
  application:
    name: sentinel-alibaba-01  # 应用名称

