# 应用服务 WEB 访问端口
server:
  port: 9093

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080   # 控制台地址
      web-context-unify: false  # 使用链路控制流量时 关闭context上下文语境
      # 添加 Sentinel 数据源的 nacos 配置,用于将规则持久化到nacos
      datasource:
        ds: # 数据源的名称, 可以随意命名
          nacos: # 表示使用 nacos 作为数据源
            server-addr: localhost:8848 # nacos服务地址
            data-id: sentinel-rules # 在Nacos中数据的ID
            username: nacos
            password: nacos
            group-id: DEFAULT_GROUP # 所属于的组
            data-type: json # 规则数据的存储类型
            rule-type: flow # 持久化的规则类型, 限流规则
            converter-class: com.alibaba.csp.sentinel.datasource.Converter # 转化规则数据为指定类型
  application:
    name: sentinel-alibaba-01  # 应用名称

